import Head from 'next/head'

export default function () {
    return (
        <>
            <Head>
                <title>Skill Assess</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <a className="navbar-brand" href="/">Navbar</a>
            </nav>
        </>
        )
}
