import Head from 'next/head'

export default function (props) {
    const toggleRandomQuestion = props.toggleRandomQuestion
    return (
        <>
            <Head>
                <title>Skill Assess</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <a className="navbar-brand ms-3" href="/">HOME</a>

                <div className="ms-auto me-3">
                    <div className="form-check form-switch">
                        <input
                            className="form-check-input"
                            type="checkbox"
                            id="answerOnly"
                            onChange={() => toggleRandomQuestion()}
                        />
                        <label className="ms-3 form-check-label" htmlFor="flexSwitchCheckDefault">
                            Random questions only
                        </label>
                    </div>
                </div>
            </nav>
        </>
        )
}
